spring:
  application:
    name: reactivespring

  profiles:
    active: local

movie:
  review:
    baseurl: http://localhost:8080/api/reviews/
  info:
    baseurl: http://localhost:8080/api/v1/movieinfos/
---
spring:
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      host: localhost
      port: 27017
      database: moviedb

---
spring:
  config:
    activate:
      on-profile: non-prod
  data:
    mongodb:
      host: localhost
      port: 27017
      database: moviedb

---
#logging:
#  level:
#    root: debug