global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-services'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['service-a:8080','service-b:8081','service-c:8082']

rule_files:
  - /etc/prometheus/rules/prom-rules.yml
